### ISSUE TITLE
adminui fails to search images at provisioning (release-20151001)

### ISSUE THREAD

**Issue by pannon** [joyent/sdc-adminui#141]
Upgraded to latest SDC release (release-20151001) and adminui fails to search and display available images in the drop-down list at the VM provisioning screen.

**Comment by askfongjojo** [comment]
@pannon - Sorry the search was broken while implementing https://smartos.org/bugview/ADMINUI-2117. The fix is in 29a2254 and will be available in release-20151015 going out tomorrow.
