### ISSUE TITLE
Incomplete list of suggested images

### ISSUE THREAD

**Issue by sigxcpu76** [joyent/sdc-adminui#173]
Provisioning a virtual machine picks up suggestions from the first 10 images (first page).

In https://github.com/joyent/sdc-adminui/blob/master/www/js/views/typeahead-image.js at line 71

```var datums = images.map(function (img) {```

should read
```var datums = images.fullCollection.map(function (img) {```

**Comment by dan-luk** [comment]
@sigxcpu76 thank you this is great finding.
Assigning to @askfongjojo to triage.

**Comment by askfongjojo** [comment]
Thanks @sigxcpu76. Logged ADMINUI-2238 for this (https://smartos.org/bugview/ADMINUI-2238) and prioritized it for fixing in an upcoming release.

**Comment by sigxcpu76** [comment]
On ADMINUI-2238: I don't know what empirical tests have shown, but the JS debugger in browser had always shown exactly 10 items in datums array.
