### ISSUE TITLE
AdminUI lacks a Delete Snapshot button

### ISSUE THREAD

**Issue by nickperry** [joyent/sdc-adminui#180]
In the Snapshots section of a VM, the GUI only presents create and rollback buttons, despite DeleteMachineSnapshot being exposed via CloudAPI. This seems to be an unintentional omission.

![image](https://cloud.githubusercontent.com/assets/159528/12248817/c5dbbe6a-b8b3-11e5-9316-06d3998d85a1.png)

**Comment by nickperry** [comment]
This should be implemented via the addition of a checkbox to the left of each snapshot name. When at least one checkbox is clicked, a red trashcan icon should appear to the left of the "Create Snapshot" button, which when clicked, requests confirmation from the user with the string "Are you sure you want to remove selected snapshots?"

**Comment by jclulow** [comment]
I think the button should probably be on the screen at all times, and say something like _"Delete Selected Snapshots"_.  It could be "greyed out" until a snapshot is selected, but hiding the button will almost certainly lead to people not noticing that you can delete things.

**Comment by nickperry** [comment]
Agreed. Although, the first approach I described was in line with how removing a NIC from a VM works currently. That is, the trash can icon only appears upon a row being selected:

![image](https://cloud.githubusercontent.com/assets/159528/12250188/f1a03978-b8bc-11e5-989a-0a87e6d14ca5.png)

![image](https://cloud.githubusercontent.com/assets/159528/12250256/761a060c-b8bd-11e5-8b8f-9f4bf15e66cc.png)

**Comment by nickperry** [comment]
Interestingly, the style on the firewall rules section is different again. There is a red trashcan to the right of each rule and upon clicking it, the rule is removed immediately without a confirmation dialogue.

**Comment by askfongjojo** [comment]
@nickperry - Thanks for the suggestion. I've logged https://smartos.org/bugview/ADMINUI-2259 to track this request. At the moment we have some inconsistencies in the delete icon presentation/navigation as you have noted. For new features, we've been sticking to the second approach (have the icon next to 'Rollback', and showing up all the time as @jclulow said). We'll attempt to clean up the overall UX over time to make things more consistent.
