### ISSUE TITLE
RBAC rules required for sub-account login

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdc-adminui#192]
I created two sub-accounts on my local SDC following the [documentation](https://docs.joyent.com/public-cloud/rbac/portal). Login into the AdminUI using the sub-accounts doesn't seem to work (even when using the `account/subaccount` syntax).

This is my current policy:
![screenshot from 2016-02-15 18-23-48](https://cloud.githubusercontent.com/assets/6614080/13046007/551773c6-d411-11e5-87ad-49777c9d7540.png)

What are the rules required for a sub-account to log into the AdminUI ? 

Would it be possible to add this to the [User management section](https://docs.joyent.com/private-cloud/users) of the documentation ?

**Comment by askfongjojo** [comment]
Hi @benjamin-bergia - The sub-account (aka sub-user) feature is not supported in AdminUI since the component is meant for SDC operators who have DC-wide access. The policies for user management like the ones you've specified are used with CloudAPI instead.

**Comment by benjamin-bergia** [comment]
Oh I see. Thank you for your help.
