### ISSUE TITLE
[Feature Request] Pick a specific IP when adding a new NIC to a zone

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdc-adminui#195]
When creating a new Zone, after selecting the network to use, we have to possibility to manually input a specific IP to use. 

This feature is very useful and I would like to be able to do the same thing when adding a new NIC to an existing zone.

**Comment by askfongjojo** [comment]
Hi @benjamin-bergia - Yes this request has been raised by other SDC users as well. We don't have an ETA for it yet. Please follow this ticket https://smartos.org/bugview/ADMINUI-2239.

**Comment by benjamin-bergia** [comment]
Ok, thanks
