### ISSUE TITLE
Zone/Server UUIDs are not "clickable" anymore

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdc-adminui#196]
When browsing the **IP Address Allocations** section of a network, it was previously possible to click on the UUID of a zone/server using a specific IP and be directly sent to the page of this specific zone/server.

It is apparently gone on 20160107.
I was previously using 20151015.

Before:
![20151015](https://cloud.githubusercontent.com/assets/6614080/13274685/280cd190-dae8-11e5-86c4-6fdc2ae0a945.png)

Now:
![20160107](https://cloud.githubusercontent.com/assets/6614080/13274692/31bc8712-dae8-11e5-8885-a5d40d617567.png)

**Comment by askfongjojo** [comment]
Hi @benjamin-bergia - We are aware of this issue and will have it fixed soon. Please follow this ticket https://smartos.org/bugview/ADMINUI-2251.

**Comment by benjamin-bergia** [comment]
Hi sorry didn't notice this. Is there any way to easily browse/search issues on https://smartos.org/bugview ?

**Comment by askfongjojo** [comment]
Fixed in c8fb8b3

Hi @benjamin-bergia - Yes the SmartOS bugview is rather primitive. There have been discussions about using something else that will make browse/search easier though there is no concrete plan for the replacement yet.
