### ISSUE TITLE
VM Detail Page breaks after adjusting KVM disks

### ISSUE THREAD

**Issue by noahmehl** [joyent/sdc-adminui#204]
We created a KVM VM, and then deleted the original disks and added an empty one (as we were imaging a server from another source).  This results in admin-ui not being able to display the VM's detail page.  I get this error in my JS console:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://sdc.domain.com/api/page/vm?uuid=0ca40fef-89a9-ecc2-92e1-e2a660486f42

When I try to browse to that URI:

{
    "message": "uuid (string) is required"
}

**Comment by noahmehl** [comment]
For anyone else's edification.  We solved the immediate problem by creating KVM images with blank drives to begin with.  But, I have a feeling that changes to VM's should reflect back to the UI without issue.

**Comment by askfongjojo** [comment]
@noahmehl, we've logged the issue as https://smartos.org/bugview/ADMINUI-2302 for follow-up. It's likely that the API was expecting a valid uuid in the disk0 image_uuid attribute. It might have been blank in this case.

It'll help if you can share with us the output of `sdc-vmapi /vms/0ca40fef-89a9-ecc2-92e1-e2a660486f42 | json disks`. Thanks!

**Comment by noahmehl** [comment]
@askfongjojo I'll need to recreate the issue.  I hope to get to that today.

Thanks!

**Comment by noahmehl** [comment]
[root@headnode ~]# sdc-vmadm get b46c75ae-b72c-6aaa-8816-d18af4e29c44 | json disks
[
  {
    "path": "/dev/zvol/rdsk/zones/b46c75ae-b72c-6aaa-8816-d18af4e29c44-disk0",
    "boot": false,
    "model": "virtio",
    "zfs_filesystem": "zones/b46c75ae-b72c-6aaa-8816-d18af4e29c44-disk0",
    "zpool": "zones",
    "size": 102400,
    "compression": "off",
    "refreservation": 102400,
    "block_size": 8192
  }
]

**Comment by noahmehl** [comment]
Also, it's the same problem if there are no disks:

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1835
Content-MD5: kqO7RauSUexmMrmPyoIZ7w==
Date: Fri, 22 Apr 2016 13:47:26 GMT
Server: VMAPI
x-request-id: bfc12d80-0890-11e6-b399-cb9154d1ba11
x-response-time: 11
x-server-name: 36edef55-0be8-434b-a5c3-f34e0821dd29
Connection: keep-alive
[]

**Comment by askfongjojo** [comment]
@noahmehl - The information is helpful. Thanks!

**Comment by noahmehl** [comment]
@askfongjojo 

From Denis:
{quote}
How would you update the disks in KVM VM? I have tried to update them using vmapi methods but validation logic did not allow me do that. Also vmapi docs says that 'disks' property can not be updated and can only be set when creating.

Please advice..
{quote}

To answer this, we are using vmadm on the local host.  We are using "remove_disks" to remove the disks, and "add_disks" to add them.  We're referencing this howto: https://wiki.smartos.org/display/DOC/Using+vmadm+to+manage+virtual+machines

**Comment by noahmehl** [comment]
I have the latest code and this does not seem to work still.  I have created some machines, and need to update the disks, and the view in adminui is still broken:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://sdc.domain.net/api/page/vm?uuid=9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7

When I try to use that URI:

{
    "message": "uuid (string) is required"
}

Thanks!

**Comment by MattR-Joyent** [comment]
I've tested this issue within version 

> release-20160804-20160804T183018Z-g71e8e54

and still witness the same behaviour as first reported.  As mentioned before using the JS editor shows the 500 error returned.

**Comment by askfongjojo** [comment]
@MattR-Joyent - Can you please capture the output of `sdc-vmapi /vms/:vm_uuid` for me please? Thanks.

**Comment by noahmehl** [comment]
@askfongjojo 

HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Content-Length: 2071
Content-MD5: /vl1k9/kl0D7GhmYAqyt/g==
Date: Fri, 14 Oct 2016 22:34:13 GMT
Server: VMAPI
x-request-id: 54f285a0-925e-11e6-8a84-3d827d07b93f
x-response-time: 10
x-server-name: 36edef55-0be8-434b-a5c3-f34e0821dd29

{
  "uuid": "9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7",
  "alias": "vm-alias-name",
  "autoboot": true,
  "brand": "kvm",
  "billing_id": "7863618b-7b4b-e763-ea61-83832c1cf9a8",
  "cpu_cap": 200,
  "cpu_shares": 32,
  "create_timestamp": "2016-06-16T16:57:37.731Z",
  "customer_metadata": {
    "root_authorized_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA263ToT3YgLd/TorSxT3SlKXmi3Tw1FEEzpaYZjyvKSm5anCt6laS+J0W1mGcUUfzEUxVJ1D3AlliIfayQ/2KOhmya4Trhiad3W23VuRROij9Ex1alE1GoX7j6ZdtaB+uUiUCyXrH0pBevPvHRl/97tP1h2GFgTg5D0R084+0+rwrla9HeETUdBU6q2BmRJaa5zAyYJ7nwJ5h5MQiL/GXJtkLxzpgwn7l0hR6hV+t+APVl6r+S/jhqLvFh28nKhrByVrkhOr8ganKrOQq0X9j8Dv4S5CpcDcUq85Or4pIH/kFCO0oqRuGi9R60LYlgzNRe4Z1LDIRbamsj/eiaynnlQ=="
  },
  "datasets": [],
  "destroyed": null,
  "firewall_enabled": false,
  "internal_metadata": {},
  "last_modified": "2016-09-15T07:43:27.000Z",
  "limit_priv": "default,-file_link_any,-net_access,-proc_fork,-proc_info,-proc_session",
  "max_locked_memory": 4352,
  "max_lwps": 1000,
  "max_physical_memory": 4352,
  "max_swap": 8192,
  "nics": [
    {
      "interface": "net0",
      "mac": "90:b8:d0:1f:bf:18",
      "vlan_id": 41,
      "nic_tag": "external",
      "gateway": "192.168.1.1",
      "gateways": [
        "192.168.1.1"
      ],
      "netmask": "255.255.255.0",
      "ip": "192.168.1.13",
      "ips": [
        "192.168.1.13/24"
      ],
      "network_uuid": "25e4033d-bba6-4488-b14b-a62df27cd010",
      "model": "virtio",
      "mtu": 1500,
      "primary": true
    }
  ],
  "owner_uuid": "1e6d87be-5ab8-c4ed-8ca9-da4b63d0742f",
  "platform_buildstamp": "20160303T211841Z",
  "quota": 10,
  "ram": 4096,
  "resolvers": [
    "192.168.1.11",
    "192.168.1.12"
  ],
  "server_uuid": "00000000-0000-0000-0000-0cc47a03effe",
  "snapshots": [],
  "state": "running",
  "tags": {},
  "zfs_filesystem": "zones/9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7",
  "zfs_io_priority": 20,
  "zone_state": "running",
  "zonepath": "/zones/9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7",
  "zpool": "zones",
  "boot_timestamp": "2016-09-15T07:43:22.000Z",
  "pid": 54850,
  "vcpus": 2,
  "cpu_type": "host",
  "disks": [
    {
      "path": "/dev/zvol/rdsk/zones/9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7-disk0",
      "boot": true,
      "model": "virtio",
      "zfs_filesystem": "zones/9ea4ec41-ba50-43e1-a0ea-eeeea984b3a7-disk0",
      "zpool": "zones",
      "size": 102400,
      "compression": "off",
      "refreservation": 102400,
      "block_size": 8192
    }
  ]
}

**Comment by noahmehl** [comment]
@askfongjojo 

Was this helpful?  Do you need anything else?

Thanks!

~Noah

**Comment by askfongjojo** [comment]
Hi @noahmehl - Sorry I looked at the fix back in April and it didn't adequately address the no image_uuid scenario. We'll follow up with an additional fix.

**Comment by askfongjojo** [comment]
Hi @noahmehl - 95baba5 should address the issue. Please give it a try and let me know if it resolves the issue. Thanks.

**Comment by noahmehl** [comment]
@askfongjojo The https://github.com/joyent/sdc-adminui/commit/95baba5b98efc2ed2716e85e5e6d3d779efe0a95 commit seems to fix our issues :).  Can you let me know when this gets into the next release?  Thanks!

**Comment by askfongjojo** [comment]
Great! The commit went into the master so it'll be part of the biweekly release tomorrow (release-20161027).
