### ISSUE TITLE
Intermittent blank page problem

### ISSUE THREAD

**Issue by foxx** [joyent/sdc-adminui#223]
There seems to be an intermittent issue where the page will show up blank when logging in or clicking on any of the menu items inside adminui.

This is what comes out of console when it fails to load;

![image](https://cloud.githubusercontent.com/assets/651797/18270487/1cbf83c4-7425-11e6-9afe-da0effcb0cdc.png)

![image](https://cloud.githubusercontent.com/assets/651797/18270523/4bb085de-7425-11e6-8a02-202b8a64eba5.png)

And this is what comes out when it does load;

![image](https://cloud.githubusercontent.com/assets/651797/18270509/35faefc2-7425-11e6-989a-28c09828f993.png)

![image](https://cloud.githubusercontent.com/assets/651797/18270531/53591b5c-7425-11e6-83d6-6b12d583e31e.png)

I'm guessing there's some sort of race condition within JS, but I'm not entirely sure where it's happening.

Attempting to call `start` manually results in the following;

```
require('adminui').start();
libs.js:1 Uncaught Error: Backbone.history has already been started(…)
```

Ping continues to show in the network log;

```
{"services":{"moray":true,"ufds":true},"time":"2016-09-06T10:31:38.267Z"}
{"services":{"moray":true,"ufds":true},"time":"2016-09-06T10:31:44.272Z"}
```

The response from `/api/auth` and `/api/services?name=cloudapi` seem to look fine to the naked eye.

I'm running `adminui release-20160804-20160804T183018Z-g71e8e54`. Tried updating to the next latest version, but ran into https://github.com/joyent/triton/issues/210

Anything else I can do to help try diagnose the bug?

**Comment by askfongjojo** [comment]
@foxx - Thank you for bringing this to our attention. We're working on a fix for it, as tracked in https://smartos.org/bugview/ADMINUI-2335.

**Comment by foxx** [comment]
Thanks for confirming @askfongjojo, I'll close this out
