### ISSUE TITLE
hosting adminui without triton headnode requirements

### ISSUE THREAD

**Issue by n1ete** [joyent/sdc-adminui#235]
short question: i am looking for a simple webui alternative to project fifo.  for managing my smartos nodes. would it be possible to selfhost the adminui without the full triton  overhead/requirements? installing it in a vm on my notebook would be an awesome usecase for me.
thanks for these awesome oss hypervisor to the whole joyent team (switched from proxmox);)

**Comment by bahamat** [comment]
No, AdminUI is a web front end to the Triton API stack, it's not capable of operating on its own.
