### ISSUE TITLE
compute node DISK UTILIZATION is NAN

### ISSUE THREAD

**Issue by angustw** [joyent/sdc-adminui#5]
disk-overview.jsx-32
usedInGB is NAN
VM state 'configured',quota is undefined:
{ uuid: '20e0e132-9d9b-6827-fb26-edb6f5de77aa',
  owner_uuid: 'd4b7c98f-ea11-689b-828d-f67e93baf6d2',
  max_physical_memory: 1024,
  zone_state: 'configured',
  state: 'configured',
  brand: 'joyent',
  cpu_cap: 300,
  last_modified: '2015-03-23T01:40:36.000Z' }

**Comment by kevinykchan** [comment]
@angustw The ```DisksOverview``` component renders the disk breakdown section within the server details view for compute nodes. It is unrelated to vms or zones.

Could you provide:
1. steps to reproduce this bug
2. the JSON output of the affected server (sdc-cnapi /servers/:uuid)

This will give me enough information to populate the state of the page on my end and reproduce the bug.

Thanks!

**Comment by lloydde** [comment]
Closing since we have not heard back from @angustw .
