### ISSUE TITLE
adminui tries to change the mtu on primary flag change

### ISSUE THREAD

**Issue by sperreault** [joyent/sdc-adminui#94]
When trying to issue an update nic request througth the admiui to flip primary nic flag between 2 nics, adminui sends in the mtu as part of the json payload and it seems to be generating the error.

JSON Payload:
{"nics":[{"interface":"net0","mac":"90:b8:d0:99:86:63","mtu":1500},{"interface":"net1","mac":"90:b8:d0:3c:9d:bb","allow_ip_spoofing":true,"allow_mac_spoofing":true,"mtu":1500,"primary":true}]}

Error in vmapi logs:
POST /vms/be69f445-d176-6a7f-a3e0-ed4775e1f3e4?action=update_nics HTTP/1.1
    x-request-id: ec9c4200-412f-11e5-b23f-4f447d8d011b
    accept: application/json
    content-type: application/json
    user-agent: restify/2.8.5 (ia32-sunos; v8/3.14.5.9; OpenSSL/1.0.1e) node/0.10.26
    date: Wed, 12 Aug 2015 20:22:59 GMT
    content-length: 192
    content-md5: 9hzARfs8m8/VCnseOqDssw==
    host: vmapi.dc1.alesium.net
    connection: keep-alive

    {
      "nics": [
        {
          "interface": "net0",
          "mac": "90:b8:d0:99:86:63",
          "mtu": 1500
        },
        {
          "interface": "net1",
          "mac": "90:b8:d0:3c:9d:bb",
          "allow_ip_spoofing": true,
          "allow_mac_spoofing": true,
          "mtu": 1500,
          "primary": true
        }
      ]
    }
    --
    HTTP/1.1 409 Conflict
    content-type: application/json
    content-length: 165
    content-md5: C5QIBJaKjmrlhJpqKDhItw==
    date: Wed, 12 Aug 2015 20:22:59 GMT
    server: VMAPI
    x-request-id: ec9c4200-412f-11e5-b23f-4f447d8d011b
    x-response-time: 6
    x-server-name: 8f89fe04-7dbe-4f5c-b192-741e7ad94bae

    {
      "code": "ValidationFailed",
      "message": "Invalid VM update parameters",
      "errors": [
        {
          "field": "nics",
          "code": "Invalid",
          "message": "'mtu' is not a valid property to update"
        }
    ]
    }
    --
    ValidationFailedError: Invalid VM update parameters
        at new ValidationFailedError (/opt/smartdc/vmapi/lib/errors.js:125:23)
        at Object.exports.validateNics (/opt/smartdc/vmapi/lib/common/validation.js:1709:15)
        at Server.updateNics (/opt/smartdc/vmapi/lib/endpoints/vms.js:696:16)
        at Server.updateVm (/opt/smartdc/vmapi/lib/endpoints/vms.js:442:19)
        at next (/opt/smartdc/vmapi/node_modules/restify/lib/server.js:731:30)
        at f (/opt/smartdc/vmapi/node_modules/restify/node_modules/once/once.js:16:25)
        at onGetVm (/opt/smartdc/vmapi/lib/interceptors.js:69:13)
        at EventEmitter.<anonymous> (/opt/smartdc/vmapi/lib/apis/moray.js:208:16)
        at EventEmitter.g (events.js:180:16)
        at EventEmitter.emit (events.js:92:17)
    --
    req.timers: {
      "handler-0": 24,
      "bunyan": 73,
      "handler-2": 383,
      "parseAccept": 196,
      "readBody": 462,
      "parseBody": 53,
      "parseDate": 36,
      "parseQueryString": 208,
      "addProxies": 18,
      "checkWfapi": 14,
      "loadVm": 3528,
      "updateVm": 517
    }

**Comment by lloydde** [comment]
@sperreault thank you for reporting this. I plan to investigate this before the end of the week.

**Comment by lloydde** [comment]
@sperreault https://smartos.org/bugview/ADMINUI-2171 is open and in progress now. Based on ADMINUI-2171, it looks like the symptom has already changed. Once we have a fix, will you be able to test it?

**Comment by sperreault** [comment]
Hi,

 Yes

On Tuesday, August 25, 2015, Lloyd Dewolf <notifications@github.com> wrote:

> @sperreault <https://github.com/sperreault>
> https://smartos.org/bugview/ADMINUI-2171 is open and in progress now.
> Based on ADMINUI-2171, it looks like the symptom has already changed. Once
> we have a fix, will you be able to test it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/sdc-adminui/issues/94#issuecomment-134747606>.
>


-- 
Sebastien Perrreault
Partner
Les Technologies Alesium Inc
P: 514-298-7193
F: 514-221-3668
E: sperreault@alesium.net

"Life's missed opportunities, at the end, may seem more poignant to us than
those we embraced--because in our imagination they have a perfection that
reality can never rival." -- Roger Ebert

**Comment by lloydde** [comment]
@sperreault would you see if the issue still reproduces in the most recent adminui release available through the `sdcadm up` channel release, adminui@release-20150903-20150903T210916Z-g18f6cc0 ?

**Comment by sperreault** [comment]
I'm scheduled to update my sdc install in 2 days, let me do a test then and keep you posted.

**Comment by askfongjojo** [comment]
@sperreault - This appears to have been resolved a while back. Please re-open if you still experience the issue.
